package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/urfave/cli/v3"
)

// homeDir is the current user's home directory, used to normalise paths in docs.
var homeDir = func() string {
	h, _ := os.UserHomeDir()
	return h
}()

func docsCmd() *cli.Command {
	return &cli.Command{
		Name:   "docs",
		Usage:  "Print the full command reference as Markdown",
		Hidden: true,
		Action: func(_ context.Context, cmd *cli.Command) error {
			fmt.Print(renderDocs(newApp()))
			return nil
		},
	}
}

// renderDocs walks the command tree depth-first and returns the Markdown reference.
func renderDocs(root *cli.Command) string {
	var b strings.Builder
	b.WriteString("# tap CLI Reference\n\n")
	b.WriteString("> Auto-generated by `tap docs`. Regenerate with `mise run docs`.\n\n")

	if root.Description != "" {
		b.WriteString(root.Description)
		b.WriteString("\n\n")
	}

	visibleFlags := filterVisibleFlags(root.Flags)
	if len(visibleFlags) > 0 {
		b.WriteString("## Global flags\n\n")
		renderFlagTable(&b, visibleFlags)
		b.WriteString("\n")
	}

	// Walk every visible command recursively, registration order, depth-first.
	walkCommands(&b, root.Commands, "tap", 2)
	return b.String()
}

func walkCommands(b *strings.Builder, cmds []*cli.Command, parentPath string, depth int) {
	for _, cmd := range cmds {
		if cmd.Hidden {
			continue
		}
		path := parentPath + " " + cmd.Name
		renderCommand(b, cmd, path, depth)
		if len(cmd.Commands) > 0 {
			walkCommands(b, cmd.Commands, path, depth+1)
		}
	}
}

func renderCommand(b *strings.Builder, cmd *cli.Command, path string, depth int) {
	fmt.Fprintf(b, "%s %s\n\n", strings.Repeat("#", depth), path)

	if cmd.Usage != "" {
		fmt.Fprintf(b, "**Usage:** %s\n\n", cmd.Usage)
	}

	// Synopsis: full path + ArgsUsage.
	if cmd.ArgsUsage != "" {
		fmt.Fprintf(b, "```\n%s %s\n```\n\n", path, cmd.ArgsUsage)
	}

	if cmd.Description != "" {
		fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(cmd.Description))
	}

	visibleFlags := filterVisibleFlags(cmd.Flags)
	if len(visibleFlags) > 0 {
		b.WriteString("**Flags:**\n\n")
		renderFlagTable(b, visibleFlags)
		b.WriteString("\n")
	}
}

// filterVisibleFlags returns flags with Hidden == false.
func filterVisibleFlags(flags []cli.Flag) []cli.Flag {
	var out []cli.Flag
	for _, f := range flags {
		if !flagIsHidden(f) {
			out = append(out, f)
		}
	}
	return out
}

func flagIsHidden(f cli.Flag) bool {
	switch v := f.(type) {
	case *cli.BoolFlag:
		return v.Hidden
	case *cli.StringFlag:
		return v.Hidden
	case *cli.IntFlag:
		return v.Hidden
	case *cli.Int64Flag:
		return v.Hidden
	case *cli.Float64Flag:
		return v.Hidden
	case *cli.DurationFlag:
		return v.Hidden
	case *cli.StringSliceFlag:
		return v.Hidden
	case *cli.IntSliceFlag:
		return v.Hidden
	}
	return false
}

// renderFlagTable writes a Markdown table row for each flag.
func renderFlagTable(b *strings.Builder, flags []cli.Flag) {
	b.WriteString("| Flag | Description | Default | Env |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, f := range flags {
		name, aliases, usage, defaultVal, env := flagFields(f)
		nameStr := "--" + name
		if len(aliases) > 0 {
			parts := make([]string, len(aliases))
			for i, a := range aliases {
				if len(a) == 1 {
					parts[i] = "-" + a
				} else {
					parts[i] = "--" + a
				}
			}
			nameStr += ", " + strings.Join(parts, ", ")
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n",
			nameStr,
			escapeMarkdownCell(usage),
			escapeMarkdownCell(defaultVal),
			escapeMarkdownCell(env),
		)
	}
}

func flagFields(f cli.Flag) (name string, aliases []string, usage string, defaultVal string, env string) {
	switch v := f.(type) {
	case *cli.BoolFlag:
		name = v.Name
		aliases = v.Aliases
		usage = v.Usage
		env = joinEnvSources(v.Sources)
		if v.Value {
			defaultVal = "true"
		}
	case *cli.StringFlag:
		name = v.Name
		aliases = v.Aliases
		usage = v.Usage
		defaultVal = v.Value
		env = joinEnvSources(v.Sources)
	case *cli.IntFlag:
		name = v.Name
		aliases = v.Aliases
		usage = v.Usage
		if v.Value != 0 {
			defaultVal = fmt.Sprintf("%d", v.Value)
		}
		env = joinEnvSources(v.Sources)
	case *cli.Int64Flag:
		name = v.Name
		aliases = v.Aliases
		usage = v.Usage
		if v.Value != 0 {
			defaultVal = fmt.Sprintf("%d", v.Value)
		}
		env = joinEnvSources(v.Sources)
	case *cli.Float64Flag:
		name = v.Name
		aliases = v.Aliases
		usage = v.Usage
		if v.Value != 0 {
			defaultVal = fmt.Sprintf("%g", v.Value)
		}
		env = joinEnvSources(v.Sources)
	case *cli.DurationFlag:
		name = v.Name
		aliases = v.Aliases
		usage = v.Usage
		if v.Value != 0 {
			defaultVal = v.Value.String()
		}
		env = joinEnvSources(v.Sources)
	case *cli.StringSliceFlag:
		name = v.Name
		aliases = v.Aliases
		usage = v.Usage
		env = joinEnvSources(v.Sources)
	case *cli.IntSliceFlag:
		name = v.Name
		aliases = v.Aliases
		usage = v.Usage
		env = joinEnvSources(v.Sources)
	default:
		name = fmt.Sprintf("%v", f)
	}
	return
}

// joinEnvSources extracts ENV var names from a cli.ValueSourceChain.
func joinEnvSources(sources cli.ValueSourceChain) string {
	return strings.Join(sources.EnvKeys(), ", ")
}

// escapeMarkdownCell prevents pipe/newline from breaking the table and
// normalises machine-specific home dir paths to ~.
func escapeMarkdownCell(s string) string {
	if homeDir != "" {
		s = strings.ReplaceAll(s, homeDir, "~")
	}
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
