/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts/index'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiScriptsRouteImport } from './routes/api/scripts'
import { Route as ScriptsSiteCommandRouteImport } from './routes/scripts/$site.$command'
import { Route as ApiScriptsSplatRouteImport } from './routes/api/scripts/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptsRoute = ApiScriptsRouteImport.update({
  id: '/api/scripts',
  path: '/api/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsSiteCommandRoute = ScriptsSiteCommandRouteImport.update({
  id: '/scripts/$site/$command',
  path: '/scripts/$site/$command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptsSplatRoute = ApiScriptsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiScriptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/scripts': typeof ApiScriptsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/usage': typeof ApiUsageRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/api/scripts/$': typeof ApiScriptsSplatRoute
  '/scripts/$site/$command': typeof ScriptsSiteCommandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/scripts': typeof ApiScriptsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/usage': typeof ApiUsageRoute
  '/scripts': typeof ScriptsIndexRoute
  '/api/scripts/$': typeof ApiScriptsSplatRoute
  '/scripts/$site/$command': typeof ScriptsSiteCommandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/scripts': typeof ApiScriptsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/usage': typeof ApiUsageRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/api/scripts/$': typeof ApiScriptsSplatRoute
  '/scripts/$site/$command': typeof ScriptsSiteCommandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/scripts'
    | '/api/search'
    | '/api/sync'
    | '/api/usage'
    | '/scripts/'
    | '/api/scripts/$'
    | '/scripts/$site/$command'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/scripts'
    | '/api/search'
    | '/api/sync'
    | '/api/usage'
    | '/scripts'
    | '/api/scripts/$'
    | '/scripts/$site/$command'
  id:
    | '__root__'
    | '/'
    | '/api/scripts'
    | '/api/search'
    | '/api/sync'
    | '/api/usage'
    | '/scripts/'
    | '/api/scripts/$'
    | '/scripts/$site/$command'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiScriptsRoute: typeof ApiScriptsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiUsageRoute: typeof ApiUsageRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
  ScriptsSiteCommandRoute: typeof ScriptsSiteCommandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scripts': {
      id: '/api/scripts'
      path: '/api/scripts'
      fullPath: '/api/scripts'
      preLoaderRoute: typeof ApiScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$site/$command': {
      id: '/scripts/$site/$command'
      path: '/scripts/$site/$command'
      fullPath: '/scripts/$site/$command'
      preLoaderRoute: typeof ScriptsSiteCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scripts/$': {
      id: '/api/scripts/$'
      path: '/$'
      fullPath: '/api/scripts/$'
      preLoaderRoute: typeof ApiScriptsSplatRouteImport
      parentRoute: typeof ApiScriptsRoute
    }
  }
}

interface ApiScriptsRouteChildren {
  ApiScriptsSplatRoute: typeof ApiScriptsSplatRoute
}

const ApiScriptsRouteChildren: ApiScriptsRouteChildren = {
  ApiScriptsSplatRoute: ApiScriptsSplatRoute,
}

const ApiScriptsRouteWithChildren = ApiScriptsRoute._addFileChildren(
  ApiScriptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiScriptsRoute: ApiScriptsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiUsageRoute: ApiUsageRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
  ScriptsSiteCommandRoute: ScriptsSiteCommandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
